"""Boarding schemas package."""

from src.modules.boarding.schemas.boarding import (
    HostelCreate,
    HostelResponse,
    HostelDetailResponse,
    DormitoryCreate,
    DormitoryResponse,
    BedCreate,
    BedResponse,
    BedDetailResponse,
    BedAllocationRequest,
    BedAllocationResponse,
    AllocateBedResponse,
    RequestLeavePassRequest,
    LeavePassResponse,
    ApproveLeavePassRequest,
    ApproveLeavePassResponse,
    RecordDepartureRequest,
    RecordDepartureResponse,
    RecordReturnRequest,
    RecordReturnResponse,
    VerifyGateExitRequest,
    VerifyGateExitResponse,
    LeavePassListResponse,
    ReportDisciplinaryIncidentRequest,
    DisciplinaryIncidentResponse,
    DisciplinaryIncidentDetailResponse,
    IssueDisciplinaryActionRequest,
    DisciplinaryActionResponse,
    IssueDisciplinaryActionResponse,
    StudentDisciplinaryRecordResponse,
)

__all__ = [
    # Hostel/Dormitory/Bed
    "HostelCreate",
    "HostelResponse",
    "HostelDetailResponse",
    "DormitoryCreate",
    "DormitoryResponse",
    "BedCreate",
    "BedResponse",
    "BedDetailResponse",
    # Bed Allocation
    "BedAllocationRequest",
    "BedAllocationResponse",
    "AllocateBedResponse",
    # Leave Pass
    "RequestLeavePassRequest",
    "LeavePassResponse",
    "ApproveLeavePassRequest",
    "ApproveLeavePassResponse",
    "RecordDepartureRequest",
    "RecordDepartureResponse",
    "RecordReturnRequest",
    "RecordReturnResponse",
    "VerifyGateExitRequest",
    "VerifyGateExitResponse",
    "LeavePassListResponse",
    # Discipline
    "ReportDisciplinaryIncidentRequest",
    "DisciplinaryIncidentResponse",
    "DisciplinaryIncidentDetailResponse",
    "IssueDisciplinaryActionRequest",
    "DisciplinaryActionResponse",
    "IssueDisciplinaryActionResponse",
    "StudentDisciplinaryRecordResponse",
]
